#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

# For development see:
# - https://immich.app/docs/developer/setup
# - https://immich.app/docs/developer/troubleshooting

name: immich-dev-environment

services:
  immich-dev-workspace:
    container_name: immich-dev-workspace
    image: immich-dev-workspace:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    volumes:
      - node_modules_server:/workspaces/immich/server/node_modules
      - node_modules_web:/workspaces/immich/web/node_modules
      - node_modules_e2e:/workspaces/immich/e2e/node_modules
      - node_modules_cli:/workspaces/immich/cli/node_modules
      - node_modules_openapi:/workspaces/immich/open-api/typescript-sdk/node_modules
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: valkey/valkey:8-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    ports:
      - 6379:6379

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.2
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'immich'
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  immich-ml:
    container_name: immich_machine_learning-dev
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: no
    healthcheck:
      disable: false
    ports:
      - 3003:3003

volumes:
  model-cache:
  postgres:
  node_modules_server:
  node_modules_web:
  node_modules_e2e:
  node_modules_cli:
  node_modules_openapi:
